### ISSUE TITLE
Unclear Directions to Start Program

### ISSUE THREAD

**Issue by BlueNothing** [Printendo/HewwoStudio#1]
I can't tell which Java executable I'm supposed to be running this with. Is it java.exe? Because that makes a command prompt flash into existence for all of a second, then it goes away.

**Comment by Printendo** [comment]
Would you happen to be using OpenJDK, by any chance?

**Comment by BlueNothing** [comment]
Nope, using java.exe from jre1.8.0_161.

**Comment by Printendo** [comment]
It turned out this person didn't know how to download it.

**Comment by BlueNothing** [comment]
Whoops, sorry. I thought I was supposed to download as zip, unzip, then run.
